// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCyCL8-iKgkmW8saV_DsF8DEbq7-dQWhM',
    appId: '1:865735998526:web:0b96feea4771fc57e8656f',
    messagingSenderId: '865735998526',
    projectId: 'weatherapp-a27d0',
    authDomain: 'weatherapp-a27d0.firebaseapp.com',
    storageBucket: 'weatherapp-a27d0.appspot.com',
    measurementId: 'G-DM7BJ9YXGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KWAhXhIZQtulZkdbtAHo7RqD3hvs1oc',
    appId: '1:865735998526:android:b68f9d84c6748969e8656f',
    messagingSenderId: '865735998526',
    projectId: 'weatherapp-a27d0',
    storageBucket: 'weatherapp-a27d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdr46sU48dEuE-wbobSYwtFDgLs5z-I10',
    appId: '1:865735998526:ios:3e44e23165cc885ee8656f',
    messagingSenderId: '865735998526',
    projectId: 'weatherapp-a27d0',
    storageBucket: 'weatherapp-a27d0.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdr46sU48dEuE-wbobSYwtFDgLs5z-I10',
    appId: '1:865735998526:ios:3e44e23165cc885ee8656f',
    messagingSenderId: '865735998526',
    projectId: 'weatherapp-a27d0',
    storageBucket: 'weatherapp-a27d0.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCyCL8-iKgkmW8saV_DsF8DEbq7-dQWhM',
    appId: '1:865735998526:web:eb63ef87fb7b0c21e8656f',
    messagingSenderId: '865735998526',
    projectId: 'weatherapp-a27d0',
    authDomain: 'weatherapp-a27d0.firebaseapp.com',
    storageBucket: 'weatherapp-a27d0.appspot.com',
    measurementId: 'G-1HQ9F6C63F',
  );
}
